create extension if not exists pgcrypto;

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  comment text not null check (char_length(trim(comment)) between 1 and 280),
  mood text not null check (mood in ('🤯', '🎨', '🥳', '😌', '🤖', '👽')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default timezone('utc', now()),
  moderated_at timestamptz
);

create index if not exists idx_feedback_status_created_at
  on public.feedback (status, created_at desc);

create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where lower(email) = lower(coalesce(auth.jwt()->>'email', ''))
  );
$$;

create or replace function public.get_feedback_stats()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with mood_counts as (
    select mood, count(*)::int as total
    from public.feedback
    where status = 'approved'
    group by mood
  )
  select jsonb_build_object(
    'count', (
      select count(*)::int
      from public.feedback
      where status = 'approved'
    ),
    'moods', jsonb_build_object(
      '🤯', coalesce((select total from mood_counts where mood = '🤯'), 0),
      '🎨', coalesce((select total from mood_counts where mood = '🎨'), 0),
      '🥳', coalesce((select total from mood_counts where mood = '🥳'), 0),
      '😌', coalesce((select total from mood_counts where mood = '😌'), 0),
      '🤖', coalesce((select total from mood_counts where mood = '🤖'), 0),
      '👽', coalesce((select total from mood_counts where mood = '👽'), 0)
    )
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

revoke all on function public.get_feedback_stats() from public;
grant execute on function public.get_feedback_stats() to anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select, insert on table public.feedback to anon, authenticated;
grant update on table public.feedback to authenticated;
grant select on table public.admin_users to authenticated;
grant usage, select on sequence public.feedback_id_seq to anon, authenticated;

alter table public.feedback enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Public can read approved feedback" on public.feedback;
create policy "Public can read approved feedback"
on public.feedback
for select
to anon, authenticated
using (status = 'approved');

drop policy if exists "Public can insert pending feedback" on public.feedback;
create policy "Public can insert pending feedback"
on public.feedback
for insert
to anon, authenticated
with check (
  status = 'pending'
  and moderated_at is null
  and char_length(trim(name)) between 1 and 60
  and char_length(trim(comment)) between 1 and 280
  and mood in ('🤯', '🎨', '🥳', '😌', '🤖', '👽')
);

drop policy if exists "Admins can read all feedback" on public.feedback;
create policy "Admins can read all feedback"
on public.feedback
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can moderate feedback" on public.feedback;
create policy "Admins can moderate feedback"
on public.feedback
for update
to authenticated
using (public.is_admin())
with check (
  public.is_admin()
  and status in ('pending', 'approved', 'rejected')
);

drop policy if exists "Admins can read admin registry" on public.admin_users;
create policy "Admins can read admin registry"
on public.admin_users
for select
to authenticated
using (public.is_admin());
